In [3]:
import pandas as pd
import numpy as np

In [1]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\anura\appdata\roaming\python\python314\site-packages (3.0.0)
Requirement already satisfied: numpy>=2.3.3 in c:\users\anura\appdata\roaming\python\python314\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anura\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\anura\appdata\roaming\python\python314\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\anura\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\anura\appdata\roaming\python\python314\site-packages (2.4.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
df=pd.read_csv("customer_shopping_behavior.csv")

In [6]:
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly

In [7]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [8]:
df.isnull().mean()

Customer ID               0.000000
Age                       0.000000
Gender                    0.000000
Item Purchased            0.000000
Category                  0.000000
Purchase Amount (USD)     0.000000
Location                  0.000000
Size                      0.000000
Color                     0.000000
Season                    0.000000
Review Rating             0.009487
Subscription Status       0.000000
Shipping Type             0.000000
Discount Applied          0.000000
Promo Code Used           0.000000
Previous Purchases        0.000000
Payment Method            0.000000
Frequency of Purchases    0.000000
dtype: float64

In [9]:
df["Review Rating"]=df.groupby("Category")["Review Rating"].transform(lambda x:x.fillna(x.median))

In [10]:
df.isnull().mean()

Customer ID               0.0
Age                       0.0
Gender                    0.0
Item Purchased            0.0
Category                  0.0
Purchase Amount (USD)     0.0
Location                  0.0
Size                      0.0
Color                     0.0
Season                    0.0
Review Rating             0.0
Subscription Status       0.0
Shipping Type             0.0
Discount Applied          0.0
Promo Code Used           0.0
Previous Purchases        0.0
Payment Method            0.0
Frequency of Purchases    0.0
dtype: float64

In [11]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [12]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

create a columns age_group

In [13]:
labels=["Young Adult","Adult","Middle.aged","Senior"]
df["age_group"]=pd.qcut(df["age"],q=4,labels=labels)

In [14]:
df["age_group"]

0       Middle.aged
1       Young Adult
2       Middle.aged
3       Young Adult
4       Middle.aged
           ...
3895          Adult
3896    Middle.aged
3897    Middle.aged
3898          Adult
3899    Middle.aged
Name: age_group, Length: 3900, dtype: category
Categories (4, str): ['Young Adult' < 'Adult' < 'Middle.aged' < 'Senior']

In [15]:
df['frequency_of_purchases'].describe()

count               3900
unique                 7
top       Every 3 Months
freq                 584
Name: frequency_of_purchases, dtype: object

In [16]:
frequency_mapping={
    "Fortnightly":14,
    "Weekly":7,
    "Monthly":30,
    "Quarterly":90,
    "Bi-Weekly":14,
    "Annually":365,
    "Every 3 Months":90}
df["frequency_purchases_days"]=df["frequency_of_purchases"].map(frequency_mapping)

In [17]:
df[["frequency_purchases_days","frequency_of_purchases"]].head(10)

   frequency_purchases_days frequency_of_purchases
0                        14            Fortnightly
1                        14            Fortnightly
2                         7                 Weekly
3                         7                 Weekly
4                       365               Annually
5                         7                 Weekly
6                        90              Quarterly
7                         7                 Weekly
8                       365               Annually
9                        90              Quarterly

In [18]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [19]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [20]:
df=df.drop('discount_applied',axis=1)

In [21]:
df

,customer_id,age,gender,item_purchased,category,purchase_amount_(usd),location,size,color,season,review_rating,subscription_status,shipping_type,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,frequency_purchases_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,14,Venmo,Fortnightly,Middle.aged,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,2,Cash,Fortnightly,Young Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,23,Credit Card,Weekly,Middle.aged,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,49,PayPal,Weekly,Young Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,31,PayPal,Annually,Middle.aged,365
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,32,Venmo,Weekly,Adult,7
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,41,Bank Transfer,Bi-Weekly,Middle.aged,14
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,24,Venmo,Quarterly,Middle.aged,90
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,24,Venmo,Weekly,Adult,7
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,33,Venmo,Quarterly,Middle.aged,90

In [22]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\anura\appdata\roaming\python\python314\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\anura\appdata\roaming\python\python314\site-packages (2.0.46)
Requirement already satisfied: greenlet>=1 in c:\users\anura\appdata\roaming\python\python314\site-packages (from sqlalchemy) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\anura\appdata\roaming\python\python314\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
pip install pyodbc

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyodbc in c:\users\anura\appdata\roaming\python\python314\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
import pyodbc
print(pyodbc.drivers())

['SQL Server', 'MySQL ODBC 9.6 ANSI Driver', 'MySQL ODBC 9.6 Unicode Driver', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

stepup the connections of postgreSQL

In [25]:
pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in c:\users\anura\appdata\roaming\python\python314\site-packages (9.5.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [26]:
import mysql.connector as connection

In [37]:
pip install psycopg2-binary sqlalchemy pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\anura\appdata\roaming\python\python314\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\anura\appdata\roaming\python\python314\site-packages (2.0.46)
Requirement already satisfied: pandas in c:\users\anura\appdata\roaming\python\python314\site-packages (3.0.0)
Requirement already satisfied: greenlet>=1 in c:\users\anura\appdata\roaming\python\python314\site-packages (from sqlalchemy) (3.3.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\anura\appdata\roaming\python\python314\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: numpy>=2.3.3 in c:\users\anura\appdata\roaming\python\python314\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\anura\appdata\roaming\python\python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\anura\appdata\roaming\python\python314\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\anura\appdata\roaming\python\python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
import mysql.connector as connection
import pandas as pd
import os
import psycopg2

In [52]:
import psycopg2

conn = psycopg2.connect(
    host="127.0.0.1",
    port=5432,
    database="postgres",  # default DB
    user="postgres",
    password="admin"
)

print("Connected successfully!")

Connected successfully!

In [55]:
from sqlalchemy import create_engine
import pandas as pd

# Create Engine (this is enough — no psycopg2 needed)
engine = create_engine("postgresql://postgres:admin@localhost:5432/customer")

df_clean = df.copy()

# Remove callable values if any
for col in df_clean.columns:
    df_clean[col] = df_clean[col].apply(lambda x: x() if callable(x) else x)

# Automatically create + insert into PostgreSQL table
df_clean.to_sql(
    "customer_shopping_behavior",
    engine,
    if_exists="replace",   # replace / append / fail
    index=False
)

print("Table created successfully!")

Table created successfully!

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               3900 non-null   int64
 1   age                       3900 non-null   int64
 2   gender                    3900 non-null   str
 3   item_purchased            3900 non-null   str
 4   category                  3900 non-null   str
 5   purchase_amount_(usd)     3900 non-null   int64
 6   location                  3900 non-null   str
 7   size                      3900 non-null   str
 8   color                     3900 non-null   str
 9   season                    3900 non-null   str
 10  review_rating             3900 non-null   object
 11  subscription_status       3900 non-null   str
 12  shipping_type             3900 non-null   str
 13  promo_code_used           3900 non-null   str
 14  previous_purchases        3900 non-null   int64
 15  payment_method            3900 non-null   str
 16  frequency_of_purchases    3900 non-null   str
 17  age_group                 3900 non-null   category
 18  frequency_purchases_days  3900 non-null   int64
dtypes: category(1), int64(5), object(1), str(12)
memory usage: 552.6+ KB